<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Data.Accessor\Data.Accessor.csproj" />
    <ProjectReference Include="..\Data.Database\Data.Database.csproj" />
  </ItemGroup>

</Project>
